make from address configurable
LeastAuthority/feedback-api pull request #18
Opened 2023-02-11 01:52 UTC by vu3rdd

Closes #17

2023-02-11 07:10 UTC, wuan approved these changes

2023-02-13 08:45 UTC, btlogy commented
I've tried to fix this w/o pushing on Friday, but @vu3rdd has been quicker: thank you @vu3rdd.
Thus, I've only pushed my changes related to Docker and the documentation.

2023-02-13 09:02 UTC, btlogy requested changes
Still not sure how to use this review thingy: see my comment about email address validation.

2023-02-13 09:04 UTC, btlogy commented on main.go
> +		from:     *fromAddressPtr,
Here thus:
```
_, err := mail.ParseAddress(*toAddressPtr)
```
And then maybe we should output both at line 110:
```
log.Printf("Feedback email will be sent from:%s to:%s\n", *fromAddressPtr, *toAddressPtr)
```
?

2023-02-13 10:01 UTC, btlogy approved these changes

2023-02-13 10:05 UTC, merged